#!/bin/bash

# Script for starting with the application server of LG
cd /home/lg/Desktop/lglab/gsoc15/FAED/faed_management_tool
source ~/.virtualenvs/faed/bin/activate
xterm -e "python manage.py runfaed $1 $2"

