# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faed_management', '0002_auto_20150810_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faed_management.Drone')),
                ('dropPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faed_management.DropPoint')),
                ('hangar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faed_management.Hangar')),
            ],
        ),
    ]
