# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faed_management', '0003_incidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='drone',
        ),
    ]
