# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faed_management', '0006_auto_20160529_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='drone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faed_management.Drone'),
        ),
    ]
